apiVersion: 1

deleteDatasources:
  - name: Nehemiah Prometheus
    orgId: 1

datasources:
  - name: Nehemiah Prometheus
    uid: nehemiah-prometheus
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_URL}
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: false
      prometheusType: Prometheus
      prometheusVersion: 3.5.0
      timeInterval: 15s
